### ISSUE TITLE
New komodo-cli RPC calls

### ISSUE THREAD

**Issue by tonymorony** [blue-santa/komodo-docs-vuepress#10]
Opening an issue how was proposed in discord discussion:

>  I've tested all non-CC  komodo-cli calls from komodo-cli help https://docs.google.com/spreadsheets/d/167KG3kRQi1ZaVXqkHv_wKClxq4z-sZoI7MCArpWROMA/edit?usp=sharing
> Some of the calls seem to be very new and non-persists at all (even with "Coming soon" status) in API documentation https://docs.komodoplatform.com/komodo/komodo-API.html which I've used as help for this test. I've marked such calls in "Comments" column - maybe will be helpful for documentation updating

**Comment by siddhartha-komodo** [comment]
Thank you, Tony.

Some of these are new and we need to document them.

Some of them have already been documented in the new streamlined documentation. For future reference, you can consider that any documentation in the VuePress release is the most current and the source for all comparisons.

I'll keep this issue open until all the new rpc calls are added.
